### ISSUE TITLE
TypeError: while_loop() got an unexpected keyword argument 'shape_invariants'

### ISSUE THREAD

**Issue by ghost** [dshieble/Music_RNN_RBM#13]
```  
0%|                                                                         | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "rnn_rbm_generate.py", line 48, in <module>
    main(sys.argv[1])
  File "rnn_rbm_generate.py", line 43, in main
    generated_music = sess.run(generate(300), feed_dict={x: song_primer}) #Prime the network with song primer and generate an original song
  File "/Users/roberthecimovic/Documents/Code/Github/poly-rnn/rnn_rbm.py", line 109, in generate
    x.get_shape(), tf.TensorShape([None, 780])])
TypeError: while_loop() got an unexpected keyword argument 'shape_invariants'
(venv) FAIL: 1
```

I had this working and then I decided to do a clean install of python and am getting stuck on the last generation step, when before this wasn't a problem at all. No idea what I'm getting wrong.

**Comment by ghost** [comment]
OK I solved it by cloning the original and replacing my copy of rnn_rbm.py. No idea what that's done.
