### ISSUE TITLE
no such file

### ISSUE THREAD

**Issue by mordigann228** [dshieble/Music_RNN_RBM#2]
Hi there, I'm having an issue. I changed the initial midi files given in the git, and now when I try to generate music it bring

> # python rnn_rbm_generate.py parameter_checkpoints/epoch_149.ckpt
Traceback (most recent call last):
  File "rnn_rbm_generate.py", line 49, in <module>
    main(sys)
  File "rnn_rbm_generate.py", line 32, in main
    song_primer = midi_manipulation.get_song(primer_song)
  File "/media/aram/Mordigan/Happy_Music_Generator-master/Music_RNN_RBM/midi_manipulation.py", line 19, in get_song
    song = np.array(midiToNoteStateMatrix(path))
  File "/media/aram/Mordigan/Happy_Music_Generator-master/Music_RNN_RBM/midi_manipulation.py", line 37, in midiToNoteStateMatrix
    pattern = midi.read_midifile(midifile)
  File "/usr/local/lib/python2.7/dist-packages/midi/fileio.py", line 156, in read_midifile
    midifile = open(midifile, 'rb')
IOError: [Errno 2] No such file or directory: 'Pop_Music_Midi/Every Time We Touch - Chorus.midi'

There should not be such a file, and I cant get how to fix this, any help?

**Comment by Peter-Sanders** [comment]
I've just encountered this error, has anyone managed a fix for it yet?

**Comment by Ddedalous** [comment]
me too

**Comment by Ddedalous** [comment]
I solved this: if you go into your parent directory and open midi_manipulation.py and change the value of the 'primer song'  variable  to the full path to any midi file you trained with it works.
