### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'music_outputs/0_Every Time We Touch - Chorus.midi.mid'

### ISSUE THREAD

**Issue by YuzukiTsuru** [dshieble/Music_RNN_RBM#9]
`
Traceback (most recent call last):
  File "rnn_rbm_generate.py", line 45, in <module>
    main(sys.argv[1])
  File "rnn_rbm_generate.py", line 42, in main
    midi_manipulation.write_song(new_song_path, generated_music)
  File "/home/gloomyghost/rbm/Music_RNN_RBM/midi_manipulation.py", line 15, in write_song
    noteStateMatrixToMidi(song, name=path)
  File "/home/gloomyghost/rbm/Music_RNN_RBM/midi_manipulation.py", line 138, in noteStateMatrixToMidi
    midi.write_midifile("{}.mid".format(name), pattern)
  File "/usr/local/lib/python2.7/dist-packages/midi/fileio.py", line 150, in write_midifile
    midifile = open(midifile, 'wb')
IOError: [Errno 2] No such file or directory: 'music_outputs/0_Every Time We Touch - Chorus.midi.mid'
`

**Comment by YuzukiTsuru** [comment]
I just make a huge mistake /sorry

**Comment by hasagar97** [comment]
What was the mistake I think I am repeating the same @740291272 .

**Comment by hasagar97** [comment]
The mistake was that Python was unable to create "music_outputs/" directory. you have to create it manually.
